### PR TITLE
fix: allow user to change password without MFA configured

### PR DESCRIPTION
**Pull request by jufemaiz**
Where a user does not have a PGP and an administrator resets the password via API/console requiring a change of password upon first authentication (enforcing unknown password beyond the user), `GetLoginProfile` and `UpdateLoginProfile` is needed.

### CODE REVIEW

**Comment by sjauld** [comment]
Why?

**Comment by jufemaiz** [comment]
> Why?

See above.

**Comment by sjauld** [comment]
Oh.

**Comment by jufemaiz** [comment]
Also, the boffins at aws thought it a good idea to let users name their MFA resources whatever they like. 🤦🏼

**Comment by jufemaiz** [comment]
Approved @sjauld?

**Review by sjauld — APPROVED** [review]
Sure.... But I didn't know you were still using this! I'll see what changes I need to add.

**Pull request merged**
